[build]
command = "npx @11ty/eleventy --input=./website"
publish = "_site"

[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"

[[plugins]]
    package = "netlify-plugin-cypress"
    [plugins.inputs]
        record = true