[build]
command = "npx @11ty/eleventy --input=./website"
publish = "_site"

[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"

[[plugins]]
    package = "netlify-plugin-cypress"
    [plugins.inputs]
        record = true

[[plugins]]
    package = "@netlify/plugin-lighthouse"
    [plugins.inputs.thresholds]
        performance = 0.95
        accessibility = 0.95
        best-practices = 0.95
        seo = 0.90
        pwa = 0