[build]
command = "npx @11ty/eleventy --input=./website"
publish = "_site"

[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"
NODE_VERSION = "14"

[[plugins]]
    package = "netlify-plugin-cypress"
    [plugins.inputs]
        record = true

[[plugins]]
    package = "@netlify/plugin-lighthouse"
    [plugins.inputs.thresholds]
        performance = 0.9
        accessibility = 0.9
        best-practices = 0.9
        seo = 0.9
        pwa = 0
        
[[plugins]]
    package = "netlify-plugin-html-validate"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://www.dertagundich.de; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "interest-cohort=()"

