[build]
command = "ELEVENTY_ENV='production' npx @11ty/eleventy --input=./website"
publish = "_site"

[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"
NODE_VERSION = "17"

[[plugins]]
    package = "netlify-plugin-cypress"
    [plugins.inputs]
        record = true

[[plugins]]
    package = "@netlify/plugin-lighthouse"
    [plugins.inputs.thresholds]
        performance = 0.9
        accessibility = 0.9
        best-practices = 0.9
        seo = 0.9
        pwa = 0
        
[[plugins]]
    package = "netlify-plugin-html-validate"

[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "interest-cohort=()"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "no-referrer-when-downgrade"
